# Generated by Django 6.0.3 on 2026-03-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                ("sender", models.CharField(db_index=True, max_length=500)),
                ("subject", models.CharField(max_length=1000)),
                ("received_at", models.DateTimeField()),
                ("snippet", models.TextField(blank=True, default="")),
                ("raw_html", models.TextField(blank=True, default="")),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("subscription", "Subscription"),
                            ("investment", "Investment"),
                            ("bill", "Bill"),
                            ("ecommerce", "E-commerce"),
                            ("bank", "Bank"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedFinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("cc_transaction", "CC Transaction"),
                            ("subscription_renewal", "Subscription Renewal"),
                            ("investment_update", "Investment Update"),
                            ("bill_notice", "Bill Notice"),
                            ("order_confirmation", "Order Confirmation"),
                            ("delivery_update", "Delivery Update"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_json", models.JSONField()),
                ("confidence", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="gmail.emailmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("refresh_token", models.TextField()),
                ("access_token", models.TextField(blank=True, default="")),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_history_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "email")},
            },
        ),
        migrations.CreateModel(
            name="EmailSenderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_pattern", models.CharField(max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("subscription", "Subscription"),
                            ("investment", "Investment"),
                            ("bill", "Bill"),
                            ("ecommerce", "E-commerce"),
                            ("bank", "Bank"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gmail_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_rules",
                        to="gmail.gmailaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="gmail_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="gmail.gmailaccount",
            ),
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetching", "Fetching"),
                            ("classifying", "Classifying"),
                            ("parsing", "Parsing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("processed_messages", models.IntegerField(default=0)),
                ("new_messages", models.IntegerField(default=0)),
                ("extracted_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gmail_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="gmail.gmailaccount",
                    ),
                ),
            ],
        ),
    ]
