# Generated by Django 6.0.3 on 2026-03-15 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedfinancialdata",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("cc_transaction", "CC Transaction"),
                    ("cc_bill", "CC Bill/Statement"),
                    ("subscription_renewal", "Subscription Renewal"),
                    ("investment_update", "Investment Update"),
                    ("bill_notice", "Bill Notice"),
                    ("order_confirmation", "Order Confirmation"),
                    ("delivery_update", "Delivery Update"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=100)),
                ("attachment_id", models.CharField(max_length=500)),
                ("size_bytes", models.IntegerField(default=0)),
                ("pdf_bytes", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="gmail.emailmessage",
                    ),
                ),
            ],
        ),
    ]
