# Generated by Django 6.0.3 on 2026-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail", "0002_alter_extractedfinancialdata_data_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedfinancialdata",
            name="is_materialized",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="extractedfinancialdata",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("cc_transaction", "CC Transaction"),
                    ("cc_bill", "CC Bill/Statement"),
                    ("bank_statement", "Bank Account Statement"),
                    ("subscription_renewal", "Subscription Renewal"),
                    ("investment_update", "Investment Update"),
                    ("bill_notice", "Bill Notice"),
                    ("order_confirmation", "Order Confirmation"),
                    ("delivery_update", "Delivery Update"),
                ],
                max_length=30,
            ),
        ),
    ]
