# Generated by Django 6.0.3 on 2026-03-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail", "0003_add_bank_statement_and_is_materialized"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsenderrule",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailsenderrule",
            name="require_attachment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailsenderrule",
            name="subject_pattern",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="needs_reauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="reauth_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_name",
                    models.CharField(
                        choices=[
                            ("fetch", "Fetch Emails"),
                            ("classify", "Classify Senders"),
                            ("parse", "Parse Emails"),
                            ("materialize", "Materialize Data"),
                            ("classify_transactions", "Classify Transactions"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "sync_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="gmail.syncjob",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
