# Generated by Django 6.0.3 on 2026-03-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail", "0004_emailsenderrule_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="sync_months",
            field=models.IntegerField(default=12),
        ),
    ]
