# Generated by Django 6.0.3 on 2026-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail", "0005_syncjob_sync_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinestep",
            name="step_name",
            field=models.CharField(
                choices=[
                    ("fetch", "Fetch Emails"),
                    ("classify", "Classify Senders"),
                    ("parse", "Parse Emails"),
                    ("materialize", "Materialize Data"),
                    ("classify_transactions", "Classify Transactions"),
                    ("detect_subscriptions", "Detect Subscriptions"),
                ],
                max_length=30,
            ),
        ),
    ]
