# Generated by Django 6.0.3 on 2026-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("groceries", "Groceries"),
                    ("clothing", "Clothing"),
                    ("entertainment", "Entertainment"),
                    ("ecommerce", "E-commerce"),
                    ("travel_transport", "Travel & Transport"),
                    ("bills_utilities", "Bills & Utilities"),
                    ("healthcare", "Healthcare"),
                    ("education", "Education"),
                    ("investment_finance", "Investment & Finance"),
                    ("services_misc", "Services & Misc"),
                    ("transfers_payments", "Transfers & Payments"),
                    ("uncategorized", "Uncategorized"),
                ],
                db_index=True,
                default="uncategorized",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="category_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_user_categorized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_channel",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="upi_handle",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
