# Generated by Django 6.0.3 on 2026-03-15 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "banking",
            "0002_transaction_category_transaction_category_confidence_and_more",
        ),
        ("gmail", "0002_alter_extractedfinancialdata_data_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        choices=[
                            ("HDFC", "HDFC Bank"),
                            ("ICICI", "ICICI Bank"),
                            ("AXIS", "Axis Bank"),
                            ("SBI", "SBI Card"),
                            ("KOTAK", "Kotak Mahindra"),
                            ("INDUSIND", "IndusInd Bank"),
                            ("RBL", "RBL Bank"),
                            ("YES", "Yes Bank"),
                            ("AMEX", "American Express"),
                            ("CITI", "Citibank"),
                            ("SC", "Standard Chartered"),
                            ("HSBC", "HSBC"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("card_last4", models.CharField(db_index=True, max_length=4)),
                ("card_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to="banking.family",
                    ),
                ),
            ],
            options={
                "unique_together": {("family", "issuer", "card_last4")},
            },
        ),
        migrations.CreateModel(
            name="CreditCardBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "total_due",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "min_due",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("billing_period_start", models.DateField(blank=True, null=True)),
                ("billing_period_end", models.DateField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="banking.creditcard",
                    ),
                ),
                (
                    "source_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gmail.emailmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date"],
                "unique_together": {("card", "statement_date")},
            },
        ),
        migrations.CreateModel(
            name="CreditCardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.TextField()),
                (
                    "merchant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("groceries", "Groceries"),
                            ("clothing", "Clothing"),
                            ("entertainment", "Entertainment"),
                            ("ecommerce", "E-commerce"),
                            ("travel_transport", "Travel & Transport"),
                            ("bills_utilities", "Bills & Utilities"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("investment_finance", "Investment & Finance"),
                            ("services_misc", "Services & Misc"),
                            ("transfers_payments", "Transfers & Payments"),
                            ("uncategorized", "Uncategorized"),
                        ],
                        db_index=True,
                        default="uncategorized",
                        max_length=30,
                    ),
                ),
                ("category_confidence", models.FloatField(default=0.0)),
                ("is_user_categorized", models.BooleanField(default=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("alert", "Email Alert"),
                            ("statement", "Statement"),
                            ("manual", "Manual"),
                        ],
                        default="alert",
                        max_length=20,
                    ),
                ),
                (
                    "dedup_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="banking.creditcardbill",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.creditcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
