# Generated by Django 6.0.3 on 2026-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_creditcard_creditcardbill_creditcardtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="cardholder_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="cardholder_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="family",
            name="cardholder_pan",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
