# Generated by Django 6.0.3 on 2026-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0004_family_cardholder_dob_family_cardholder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardtransaction",
            name="transaction_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
