# Generated by Django 6.0.3 on 2026-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0005_creditcardtransaction_transaction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardtransaction",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
