# Generated by Django 6.0.3 on 2026-03-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0006_creditcardtransaction_currency"),
        ("gmail", "0002_alter_extractedfinancialdata_data_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("merchant_pattern", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("streaming", "Streaming"),
                            ("music", "Music"),
                            ("cloud", "Cloud Storage"),
                            ("productivity", "Productivity"),
                            ("gaming", "Gaming"),
                            ("news", "News"),
                            ("fitness", "Fitness"),
                            ("education", "Education"),
                            ("finance", "Finance"),
                            ("shopping", "Shopping"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("next_renewal_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("last_billed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                ("icon", models.CharField(blank=True, default="", max_length=10)),
                ("color", models.CharField(blank=True, default="", max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("plan", models.CharField(blank=True, default="", max_length=100)),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bank_txn", "Bank Transaction"),
                            ("cc_txn", "Credit Card Transaction"),
                            ("email", "Email"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="banking.family",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_billed_date"],
                "unique_together": {("family", "merchant_pattern", "cycle")},
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="banking.transaction",
                    ),
                ),
                (
                    "cc_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="banking.creditcardtransaction",
                    ),
                ),
                (
                    "source_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gmail.emailmessage",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="banking.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
