# Generated by Django 6.0.3 on 2026-03-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0007_subscription_subscriptionpayment"),
        ("gmail", "0002_alter_extractedfinancialdata_data_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardbill",
            name="payment_bank_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The bank statement debit that paid this CC bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_bill_payments",
                to="banking.transaction",
            ),
        ),
        migrations.CreateModel(
            name="UnifiedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "merchant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("groceries", "Groceries"),
                            ("clothing", "Clothing"),
                            ("entertainment", "Entertainment"),
                            ("ecommerce", "E-commerce"),
                            ("travel_transport", "Travel & Transport"),
                            ("bills_utilities", "Bills & Utilities"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("investment_finance", "Investment & Finance"),
                            ("services_misc", "Services & Misc"),
                            ("transfers_payments", "Transfers & Payments"),
                            ("uncategorized", "Uncategorized"),
                        ],
                        db_index=True,
                        default="uncategorized",
                        max_length=30,
                    ),
                ),
                ("category_confidence", models.FloatField(default=0.0)),
                ("is_user_categorized", models.BooleanField(default=False)),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("bank_debit", "Bank Debit"),
                            ("bank_credit", "Bank Credit"),
                            ("credit_card", "Credit Card"),
                            ("upi", "UPI"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_transactions",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_transactions",
                        to="banking.creditcard",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_transactions",
                        to="banking.family",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("bank_statement", "Bank Statement"),
                            ("cc_alert_email", "CC Alert Email"),
                            ("cc_statement_pdf", "CC Statement PDF"),
                            ("subscription_email", "Subscription Email"),
                            ("ecommerce_email", "E-commerce Email"),
                            ("bill_email", "Bill Email"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=30,
                    ),
                ),
                ("raw_description", models.TextField(blank=True, default="")),
                (
                    "raw_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "raw_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_sources",
                        to="banking.transaction",
                    ),
                ),
                (
                    "cc_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_sources",
                        to="banking.creditcardtransaction",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gmail.emailmessage",
                    ),
                ),
                (
                    "extracted_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gmail.extractedfinancialdata",
                    ),
                ),
                (
                    "unified_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="banking.unifiedtransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="creditcardtransaction",
            name="unified_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_transactions",
                to="banking.unifiedtransaction",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="unified_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_payments",
                to="banking.unifiedtransaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="unified_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions",
                to="banking.unifiedtransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedtransaction",
            index=models.Index(
                fields=["family", "transaction_date"],
                name="banking_uni_family__ccaad2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedtransaction",
            index=models.Index(
                fields=["family", "category"], name="banking_uni_family__0bd0da_idx"
            ),
        ),
    ]
