# Generated by Django 6.0.3 on 2026-03-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "banking",
            "0002_transaction_category_transaction_category_confidence_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCategoryOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_category", models.CharField(max_length=30)),
                ("new_category", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_overrides",
                        to="banking.transaction",
                    ),
                ),
            ],
        ),
    ]
